const products = [
  {
    id: 0,
    name: "alphonso mango",
    desc: "great Quality of Mango",
    type: "fruits",
    banner: "alphonso.jpeg",
    unit: 1,
    price: 300,
    available: true,
    suplier: "Golden seed firming",
  },
  {
    id: 1,
    name: "Apples",
    desc: "great Quality of Apple",
    type: "fruits",
    banner: "apples.jpeg",
    unit: 1,
    price: 140,
    available: true,
    suplier: "Golden seed firming",
  },
  {
    id: 2,
    name: "Kesar Mango",
    desc: "great Quality of Mango",
    type: "fruits",
    banner: "kesar.jpeg",
    unit: 1,
    price: 170,
    available: true,
    suplier: "Golden seed firming",
  },
  {
    id: 3,
    name: "Langra Mango",
    desc: "great Quality of Mango",
    type: "fruits",
    banner: "langra.jpeg",
    unit: 1,
    price: 280,
    available: true,
    suplier: "Golden seed firming",
  },
  {
    id: 4,
    name: "Broccoli",
    desc: "great Quality of Fresh Vegetable",
    type: "vegetables",
    banner: "broccoli.jpeg",
    unit: 1,
    price: 280,
    available: true,
    suplier: "Golden seed firming",
  },
  {
    id: 5,
    name: "Cauliflower",
    desc: "great Quality of Fresh Vegetable",
    type: "vegetables",
    banner: "cauliflower.jpeg",
    unit: 1,
    price: 280,
    available: true,
    suplier: "Golden seed firming",
  },
  {
    id: 6,
    name: "Olive Oil",
    desc: "great Quality of Oil",
    type: "oils",
    banner: "oliveoil.jpg",
    unit: 1,
    price: 400,
    available: true,
    suplier: "Golden seed firming",
  },
];
module.exports = { products };
